name: Create Release

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set variables
        run: |
          version=$(cat silence/__init__.py | perl -0 -ne 'print $1 if s|.*__version__ = ["'"'"'](.*?)['"'"'"]||')
          prerelease=$(if [[ "$version" == 0.* ]] ; then printf "true"; else printf "false"; fi)
          echo "release_name=$version" >> $GITHUB_ENV
          version=${version//./\\.}   
          changelog="$(cat CHANGELOG.md | perl -0 -ne 'print $1 if s|.*?#\s*'"$version"'.*?\n(.*?)\n#.*||s')"
          changelog="${changelog//'%'/'%25'}"
          changelog="${changelog//$'\n'/'%0A'}"
          changelog="${changelog//$'\r'/'%0D'}"
          echo "release_info=$changelog" >> $GITHUB_ENV
          echo "prerelease=$prerelease" >> $GITHUB_ENV
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.release_name }}
          release_name: ${{ env.release_name }}
          body: |
            Changelog:
            ${{ env.release_info }}
          draft: false
          prerelease: ${{ env.prerelease }}